site_name: FastAPI Backend
site_url: https://github.com/fastapi-backend-tutorial
theme:
  name: material
  font:
    text: Roboto
  language: en 
  features:
    - content.code.copy
    - content.code.select
extra:
  version:
    provider: mike


